[build]
publish = "_site"
command = "npm run build"

[template.environment]
OAUTH_CLIENT_ID = "Your OAuth Client ID"
OAUTH_CLIENT_SECRET = "Your OAuth Client Secret"

[[redirects]]
from = "/secure/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/"
to = "/secure/"
status = 302
force = true

  [redirects.conditions]
  Cookie = [ "_token" ]
